set -g prefix C-a
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind i split-window -h
bind t split-window -v
set -g status-style "fg=#cdd6f4,bg=#1e1e2e"
set -g status-position top
set -g status-left "#[fg=#cba6f7,bold] #S #[fg=#cba6f7,nobold] | "
set -g status-left-length 100
set -g window-status-format " #I:#W"
set -g window-status-current-format "#[fg=#cba6f7,bold] #[underscore]#I:#W"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#cdd6f4"
set -g message-style "fg=#cdd6f4,bg=#1e1e2e"
