console_title_template = '{{ .Shell }} in {{ .Folder }}'
final_space = true
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
[[blocks.segments]]
  type = 'path'
  style = 'plain'
  background = 'transparent'
  foreground = 'blue'
  template = '{{ .Path }}'
[blocks.segments.properties]
  style = 'full'
[[blocks.segments]]
  type = 'git'
  style = 'plain'
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
[[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'transparent'
  foreground = 'magenta'
  template = '❯'
[transient_prompt]
  background = 'transparent'
  foreground = 'magenta'
  template = '❯ '
